package com.example.newsgb.utils.ui

import com.example.newsgb.R

enum class Countries(val nameResId: Int, val countryCode: String) {
    RUSSIA(nameResId = R.string.country_russia, countryCode = "ru"),
    AUSTRALIA(nameResId = R.string.country_australia, countryCode = "au"),
    UNITED_ARAB_EMIRATES(nameResId = R.string.country_united_arab_emirates, countryCode = "ae"),
    ARGENTINA(nameResId = R.string.country_argentina, countryCode = "ar"),
    AUSTRIA(nameResId = R.string.country_austria, countryCode = "au"),
    BELGIUM(nameResId = R.string.country_belgium, countryCode = "be"),
    BULGARIA(nameResId = R.string.country_bulgaria, countryCode = "bg"),
    BRAZIL(nameResId = R.string.country_brazil, countryCode = "br"),
    CANADA(nameResId = R.string.country_canada, countryCode = "ca"),
    SWITZERLAND(nameResId = R.string.country_switzerland, countryCode = "ch"),
    CHINA(nameResId = R.string.country_china, countryCode = "cn"),
    COLOMBIA(nameResId = R.string.country_colombia, countryCode = "co"),
    CUBA(nameResId = R.string.country_cuba, countryCode = "cu"),
    CZECH_REPUBLIC(nameResId = R.string.country_czech_republic, countryCode = "cz"),
    GERMANY(nameResId = R.string.country_germany, countryCode = "de"),
    EGYPT(nameResId = R.string.country_egypt, countryCode = "eg"),
    FRANCE(nameResId = R.string.country_france, countryCode = "fr"),
    UNITED_KINGDOM(nameResId = R.string.country_united_kingdom, countryCode = "gb"),
    GREECE(nameResId = R.string.country_greece, countryCode = "gr"),
    HONG_KONG(nameResId = R.string.country_hong_kong, countryCode = "hk"),
    HUNGARY(nameResId = R.string.country_hungary, countryCode = "hu"),
    INDONESIA(nameResId = R.string.country_indonesia, countryCode = "id"),
    IRELAND(nameResId = R.string.country_ireland, countryCode = "ie"),
    ISRAEL(nameResId = R.string.country_israel, countryCode = "il"),
    INDIA(nameResId = R.string.country_india, countryCode = "in"),
    ITALY(nameResId = R.string.country_italy, countryCode = "it"),
    JAPAN(nameResId = R.string.country_japan, countryCode = "jp"),
    KOREA(nameResId = R.string.country_korea, countryCode = "kr"),
    LITHUANIA(nameResId = R.string.country_lithuania, countryCode = "lt"),
    LATVIA(nameResId = R.string.country_latvia, countryCode = "lv"),
    MOROCCO(nameResId = R.string.country_morocco, countryCode = "ma"),
    MEXICO(nameResId = R.string.country_mexico, countryCode = "mx"),
    MALAYSIA(nameResId = R.string.country_malaysia, countryCode = "my"),
    NIGERIA(nameResId = R.string.country_nigeria, countryCode = "ng"),
    NETHERLANDS(nameResId = R.string.country_netherlands, countryCode = "nl"),
    NORWAY(nameResId = R.string.country_norway, countryCode = "no"),
    NEW_ZEALAND(nameResId = R.string.country_new_zealand, countryCode = "nz"),
    PHILIPPINES(nameResId = R.string.country_philippines, countryCode = "ph"),
    POLAND(nameResId = R.string.country_poland, countryCode = "pl"),
    PORTUGAL(nameResId = R.string.country_portugal, countryCode = "pt"),
    ROMANIA(nameResId = R.string.country_romania, countryCode = "ro"),
    SERBIA(nameResId = R.string.country_serbia, countryCode = "rs"),
    SAUDI_ARABIA(nameResId = R.string.country_saudi_arabia, countryCode = "sa"),
    SWEDEN(nameResId = R.string.country_sweden, countryCode = "se"),
    SINGAPORE(nameResId = R.string.country_singapore, countryCode = "sg"),
    SLOVENIA(nameResId = R.string.country_slovenia, countryCode = "si"),
    SLOVAKIA(nameResId = R.string.country_slovakia, countryCode = "sk"),
    THAILAND(nameResId = R.string.country_thailand, countryCode = "th"),
    TURKEY(nameResId = R.string.country_turkey, countryCode = "tr"),
    TAIWAN(nameResId = R.string.country_taiwan, countryCode = "tw"),
    UKRAINE(nameResId = R.string.country_ukraine, countryCode = "ua"),
    USA(nameResId = R.string.country_usa, countryCode = "us"),
    VENEZUELA(nameResId = R.string.country_venezuela, countryCode = "ve"),
    SOUTH_AFRICA(nameResId = R.string.country_south_africa, countryCode = "za")
}